"""Add context column to Topic model

Revision ID: 368669cad2ff
Revises: 
Create Date: 2025-09-06 06:46:24.763962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368669cad2ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('context')

    # ### end Alembic commands ###
